export type InteractionType = "New Request" | "Follow-up" | "Quote Sent";

export type Email = {
  id: string;
  sender: string;
  subject: string;
  snippet: string;
  body: string;
  receivedAt: string;
  status: InteractionType;
  from: string;
  to: string;
  date: string;
};

export type DetectedFields = {
  customer: string;
  interactionType: InteractionType;
  originCity: string;
  originState: string;
  destinationCity: string;
  destinationState: string;
  equipment: string;
  weight: string;
  targetPrice: string;
  pickupDate: string;
  deliveryDate: string;
  messageId: string;
  confidence: number;
};

export const mockEmails: Email[] = [
  {
    id: "1",
    sender: "LogiTrans LLC",
    subject: "Quote Request: Dallas to Atlanta",
    snippet: "We need a quote for a full truckload, dry van, from Dallas, TX to Atlanta, GA...",
    body: `Hi Team,\n\nWe need a quote for a full truckload, dry van, from Dallas, TX to Atlanta, GA. The weight is approximately 42,000 lbs. Please provide your best rate. Pickup is scheduled for 2024-07-25 and delivery for 2024-07-28.\n\nThanks,\nJohn @ LogiTrans`,
    receivedAt: "2 hours ago",
    status: "New Request",
    from: "john@logitrans.com",
    to: "quotes@freightsight.com",
    date: "July 22, 2024, 10:30 AM",
  },
  {
    id: "2",
    sender: "QuickShip Inc.",
    subject: "Any update on quote #5821?",
    snippet: "Just following up on the quote request from yesterday for the Chicago to Miami lane.",
    body: `Hi,\n\nJust following up on the quote request from yesterday for the Chicago, IL to Miami, FL lane. Any update on quote #5821?\n\nBest,\nSarah`,
    receivedAt: "5 hours ago",
    status: "Follow-up",
    from: "sarah@quickship.com",
    to: "sales@freightsight.com",
    date: "July 22, 2024, 7:15 AM",
  },
  {
    id: "3",
    sender: "FreightSight Internal",
    subject: "Confirmation: Quote Sent to Global Movers",
    snippet: "Quote for lane Los Angeles, CA to Seattle, WA has been sent. Rate: $2,800.",
    body: `This is a confirmation that the quote for Global Movers has been sent.\n\nLane: Los Angeles, CA to Seattle, WA\nEquipment: Reefer\nRate: $2,800\n\n-The System`,
    receivedAt: "1 day ago",
    status: "Quote Sent",
    from: "system@freightsight.com",
    to: "team@freightsight.com",
    date: "July 21, 2024, 4:55 PM",
  },
  {
    id: "4",
    sender: "HeavyHaul Logistics",
    subject: "Urgent Flatbed Quote: Denver to Houston",
    snippet: "Need pricing for a flatbed shipment from Denver, CO to Houston, TX, 48,000 lbs.",
    body: `Team,\n\nI need urgent pricing for a flatbed shipment from Denver, CO to Houston, TX. Total weight is 48,000 lbs of construction materials. Pickup needed by 2024-07-26.\n\nRegards,\nMike`,
    receivedAt: "1 day ago",
    status: "New Request",
    from: "mike@heavyhaul.com",
    to: "quotes@freightsight.com",
    date: "July 21, 2024, 11:00 AM",
  },
  {
    id: "5",
    sender: "CrossCountry Carriers",
    subject: "Re: Your Quote for Phoenix to Portland",
    snippet: "Thanks for the quote. Can you do any better on the price?",
    body: `Hi there,\n\nThanks for the quote on the Phoenix, AZ to Portland, OR lane. The rate of $2,200 is a bit high. Can you do any better on the price? Our target is closer to $2,000.\n\nThanks,\nBrenda`,
    receivedAt: "2 days ago",
    status: "Follow-up",
    from: "brenda@crosscountry.com",
    to: "sales@freightsight.com",
    date: "July 20, 2024, 9:12 AM",
  },
  {
    id: "6",
    sender: "FreshDirect Produce",
    subject: "Reefer needed - Fresno, CA to Boston, MA",
    snippet: "Requesting a quote for a reefer truck. 38,000 lbs of produce.",
    body: `Hello,\n\nWe are requesting a quote for a reefer truck from Fresno, CA to Boston, MA. Load is 38,000 lbs of produce. Must maintain 34°F. Pickup 2024-07-28, deliver by 2024-08-02.\n\nThank you,\nCarlos`,
    receivedAt: "2 days ago",
    status: "New Request",
    from: "carlos@freshdirect.com",
    to: "quotes@freightsight.com",
    date: "July 20, 2024, 8:30 AM",
  },
  {
    id: "7",
    sender: "FreightSight Internal",
    subject: "Confirmation: Quote Sent to SteelWorks",
    snippet: "Quote for lane Pittsburgh, PA to Detroit, MI has been sent. Rate: $950.",
    body: `This is a confirmation that the quote for SteelWorks has been sent.\n\nLane: Pittsburgh, PA to Detroit, MI\nEquipment: Dry Van\nRate: $950\n\n-The System`,
    receivedAt: "3 days ago",
    status: "Quote Sent",
    from: "system@freightsight.com",
    to: "team@freightsight.com",
    date: "July 19, 2024, 3:00 PM",
  },
  {
    id: "8",
    sender: "Parts Express",
    subject: "LTL Quote: Newark, NJ to Philadelphia, PA",
    snippet: "Need a quote for a small LTL shipment, 4 pallets, 2,000 lbs.",
    body: `Hi,\n\nWe need a quote for a small LTL shipment from Newark, NJ to Philadelphia, PA. It's 4 pallets, total weight 2,000 lbs. Standard dry van is fine.\n\nThanks,\nDave`,
    receivedAt: "3 days ago",
    status: "New Request",
    from: "dave@partsexpress.com",
    to: "quotes@freightsight.com",
    date: "July 19, 2024, 1:20 PM",
  },
  {
    id: "9",
    sender: "LogiTrans LLC",
    subject: "Re: Quote #5819 - Follow up",
    snippet: "Checking in on the status of our request for the Dallas to Atlanta lane.",
    body: `Hello Team,\n\nI am checking in on the status of our request for the Dallas, TX to Atlanta, GA lane, quote #5819. Have you had a chance to look at it?\n\nThanks,\nJohn`,
    receivedAt: "3 days ago",
    status: "Follow-up",
    from: "john@logitrans.com",
    to: "sales@freightsight.com",
    date: "July 19, 2024, 10:05 AM",
  },
  {
    id: "10",
    sender: "BuildMart Supplies",
    subject: "Flatbed required: Salt Lake City to Las Vegas",
    snippet: "We have a load of lumber, 45,000 lbs, needing a flatbed.",
    body: `Hi FreightSight,\n\nWe have a load of lumber, 45,000 lbs, needing a flatbed from Salt Lake City, UT to Las Vegas, NV. Flexible pickup dates, next week is fine (2024-07-29 - 2024-08-02).\n\nLet me know the rate.\n\nSteve`,
    receivedAt: "4 days ago",
    status: "New Request",
    from: "steve@buildmart.com",
    to: "quotes@freightsight.com",
    date: "July 18, 2024, 5:00 PM",
  },
  {
    id: "11",
    sender: "FreightSight Internal",
    subject: "Confirmation: Quote Sent to QuickShip",
    snippet: "Quote for lane Chicago, IL to Miami, FL has been sent. Rate: $3,500.",
    body: `This is a confirmation that the quote for QuickShip Inc. has been sent.\n\nLane: Chicago, IL to Miami, FL\nEquipment: Dry Van\nRate: $3,500\n\n-The System`,
    receivedAt: "4 days ago",
    status: "Quote Sent",
    from: "system@freightsight.com",
    to: "team@freightsight.com",
    date: "July 18, 2024, 2:10 PM",
  },
  {
    id: "12",
    sender: "Global Movers",
    subject: "Re: Your Quote for LA to Seattle",
    snippet: "The $2,800 rate for the reefer is approved. Please book it.",
    body: `Team,\n\nThe $2,800 rate for the reefer from Los Angeles, CA to Seattle, WA is approved. Please book it for pickup on 2024-07-27.\n\nThanks,\nAnna`,
    receivedAt: "5 days ago",
    status: "Follow-up",
    from: "anna@globalmovers.com",
    to: "sales@freightsight.com",
    date: "July 17, 2024, 11:45 AM",
  },
  {
    id: "13",
    sender: "Agri-Source",
    subject: "Pricing for Grain Shipment - Omaha, NE to Kansas City, MO",
    snippet: "Need a quote for a hopper bottom trailer, 50,000 lbs of corn.",
    body: `Hello,\n\nWe are looking for pricing on a grain shipment from Omaha, NE to Kansas City, MO. We will need a hopper bottom trailer for 50,000 lbs of corn. Pickup can be anytime next week.\n\n- Agri-Source Team`,
    receivedAt: "5 days ago",
    status: "New Request",
    from: "contact@agri-source.com",
    to: "quotes@freightsight.com",
    date: "July 17, 2024, 10:00 AM",
  },
  {
    id: "14",
    sender: "SteelWorks",
    subject: "Checking on quote from last week",
    snippet: "Hi, I sent a request for a Pittsburgh to Detroit quote last week, any news?",
    body: `Hi,\n\nI sent a request for a Pittsburgh, PA to Detroit, MI quote last week, any news on that?\n\nThanks,\nFrank`,
    receivedAt: "6 days ago",
    status: "Follow-up",
    from: "frank@steel.works",
    to: "sales@freightsight.com",
    date: "July 16, 2024, 9:30 AM",
  },
  {
    id: "15",
    sender: "ChemTransport",
    subject: "Tanker Quote: Baton Rouge, LA to Memphis, TN",
    snippet: "Need a quote for a tanker truck, non-hazmat liquid, 40,000 lbs.",
    body: `Hi,\n\nWe need a quote for a tanker truck to move non-hazmat liquid from Baton Rouge, LA to Memphis, TN. Weight is 40,000 lbs. Pickup on 2024-08-01.\n\nBest,\nSusan`,
    receivedAt: "1 week ago",
    status: "New Request",
    from: "susan@chemtransport.com",
    to: "quotes@freightsight.com",
    date: "July 15, 2024, 2:00 PM",
  },
];

export const mockDetectedFields: Record<string, DetectedFields> = {
  "1": {
    customer: "LogiTrans LLC",
    interactionType: "New Request",
    originCity: "Dallas",
    originState: "TX",
    destinationCity: "Atlanta",
    destinationState: "GA",
    equipment: "Dry Van",
    weight: "42,000 lbs",
    targetPrice: "N/A",
    pickupDate: "2024-07-25",
    deliveryDate: "2024-07-28",
    messageId: "msg-1a2b3c4d5e",
    confidence: 95,
  },
  "2": {
    customer: "QuickShip Inc.",
    interactionType: "Follow-up",
    originCity: "Chicago",
    originState: "IL",
    destinationCity: "Miami",
    destinationState: "FL",
    equipment: "Unknown",
    weight: "N/A",
    targetPrice: "N/A",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-6f7g8h9i0j",
    confidence: 88,
  },
  "3": {
    customer: "Global Movers",
    interactionType: "Quote Sent",
    originCity: "Los Angeles",
    originState: "CA",
    destinationCity: "Seattle",
    destinationState: "WA",
    equipment: "Reefer",
    weight: "N/A",
    targetPrice: "$2,800",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-k1l2m3n4o5",
    confidence: 99,
  },
  "4": {
    customer: "HeavyHaul Logistics",
    interactionType: "New Request",
    originCity: "Denver",
    originState: "CO",
    destinationCity: "Houston",
    destinationState: "TX",
    equipment: "Flatbed",
    weight: "48,000 lbs",
    targetPrice: "N/A",
    pickupDate: "2024-07-26",
    deliveryDate: "N/A",
    messageId: "msg-p6q7r8s9t0",
    confidence: 96,
  },
  "5": {
    customer: "CrossCountry Carriers",
    interactionType: "Follow-up",
    originCity: "Phoenix",
    originState: "AZ",
    destinationCity: "Portland",
    destinationState: "OR",
    equipment: "Unknown",
    weight: "N/A",
    targetPrice: "$2,000",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-u1v2w3x4y5",
    confidence: 85,
  },
    "6": {
    customer: "FreshDirect Produce",
    interactionType: "New Request",
    originCity: "Fresno",
    originState: "CA",
    destinationCity: "Boston",
    destinationState: "MA",
    equipment: "Reefer",
    weight: "38,000 lbs",
    targetPrice: "N/A",
    pickupDate: "2024-07-28",
    deliveryDate: "2024-08-02",
    messageId: "msg-z6a7b8c9d0",
    confidence: 94,
  },
  "7": {
    customer: "SteelWorks",
    interactionType: "Quote Sent",
    originCity: "Pittsburgh",
    originState: "PA",
    destinationCity: "Detroit",
    destinationState: "MI",
    equipment: "Dry Van",
    weight: "N/A",
    targetPrice: "$950",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-e1f2g3h4i5",
    confidence: 99,
  },
  "8": {
    customer: "Parts Express",
    interactionType: "New Request",
    originCity: "Newark",
    originState: "NJ",
    destinationCity: "Philadelphia",
    destinationState: "PA",
    equipment: "Dry Van",
    weight: "2,000 lbs",
    targetPrice: "N/A",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-j6k7l8m9n0",
    confidence: 91,
  },
    "9": {
    customer: "LogiTrans LLC",
    interactionType: "Follow-up",
    originCity: "Dallas",
    originState: "TX",
    destinationCity: "Atlanta",
    destinationState: "GA",
    equipment: "Unknown",
    weight: "N/A",
    targetPrice: "N/A",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-o1p2q3r4s5",
    confidence: 82,
  },
  "10": {
    customer: "BuildMart Supplies",
    interactionType: "New Request",
    originCity: "Salt Lake City",
    originState: "UT",
    destinationCity: "Las Vegas",
    destinationState: "NV",
    equipment: "Flatbed",
    weight: "45,000 lbs",
    targetPrice: "N/A",
    pickupDate: "2024-07-29",
    deliveryDate: "2024-08-02",
    messageId: "msg-t6u7v8w9x0",
    confidence: 93,
  },
  "11": {
    customer: "QuickShip Inc.",
    interactionType: "Quote Sent",
    originCity: "Chicago",
    originState: "IL",
    destinationCity: "Miami",
    destinationState: "FL",
    equipment: "Dry Van",
    weight: "N/A",
    targetPrice: "$3,500",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-y1z2a3b4c5",
    confidence: 98,
  },
  "12": {
    customer: "Global Movers",
    interactionType: "Follow-up",
    originCity: "Los Angeles",
    originState: "CA",
    destinationCity: "Seattle",
    destinationState: "WA",
    equipment: "Reefer",
    weight: "N/A",
    targetPrice: "$2,800",
    pickupDate: "2024-07-27",
    deliveryDate: "N/A",
    messageId: "msg-d6e7f8g9h0",
    confidence: 90,
  },
    "13": {
    customer: "Agri-Source",
    interactionType: "New Request",
    originCity: "Omaha",
    originState: "NE",
    destinationCity: "Kansas City",
    destinationState: "MO",
    equipment: "Hopper Bottom",
    weight: "50,000 lbs",
    targetPrice: "N/A",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-i1j2k3l4m5",
    confidence: 89,
  },
  "14": {
    customer: "SteelWorks",
    interactionType: "Follow-up",
    originCity: "Pittsburgh",
    originState: "PA",
    destinationCity: "Detroit",
    destinationState: "MI",
    equipment: "Unknown",
    weight: "N/A",
    targetPrice: "N/A",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-n6o7p8q9r0",
    confidence: 75,
  },
  "15": {
    customer: "ChemTransport",
    interactionType: "New Request",
    originCity: "Baton Rouge",
    originState: "LA",
    destinationCity: "Memphis",
    destinationState: "TN",
    equipment: "Tanker",
    weight: "40,000 lbs",
    targetPrice: "N/A",
    pickupDate: "2024-08-01",
    deliveryDate: "N/A",
    messageId: "msg-s1t2u3v4w5",
    confidence: 92,
  },
};
