export type InteractionType = "New Request" | "Follow-up" | "Quote Sent";
export type LogStatus = "Logged" | "Verified" | "Error";

export type LogEntry = {
  timestamp: string;
  interactionType: InteractionType;
  customer: string;
  originCity: string;
  originState: string;
  destinationCity: string;
  destinationState: string;
  equipment: string;
  weight: string;
  targetPrice: string;
  pickupDate: string;
  deliveryDate: string;
  messageId: string;
  confidence: number;
  status: LogStatus;
};

export const mockLogs: LogEntry[] = [
  {
    timestamp: "2024-07-22T12:30:00Z",
    interactionType: "New Request",
    customer: "LogiTrans LLC",
    originCity: "Dallas",
    originState: "TX",
    destinationCity: "Atlanta",
    destinationState: "GA",
    equipment: "Dry Van",
    weight: "42,000 lbs",
    targetPrice: "$2500",
    pickupDate: "2024-07-25",
    deliveryDate: "2024-07-28",
    messageId: "msg-1a2b3c4d5e",
    confidence: 95,
    status: "Logged",
  },
  {
    timestamp: "2024-07-22T09:15:00Z",
    interactionType: "Follow-up",
    customer: "QuickShip Inc.",
    originCity: "Chicago",
    originState: "IL",
    destinationCity: "Miami",
    destinationState: "FL",
    equipment: "Dry Van",
    weight: "N/A",
    targetPrice: "$3500",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-6f7g8h9i0j",
    confidence: 88,
    status: "Logged",
  },
  {
    timestamp: "2024-07-21T16:55:00Z",
    interactionType: "Quote Sent",
    customer: "Global Movers",
    originCity: "Los Angeles",
    originState: "CA",
    destinationCity: "Seattle",
    destinationState: "WA",
    equipment: "Reefer",
    weight: "35,000 lbs",
    targetPrice: "$2,800",
    pickupDate: "2024-07-24",
    deliveryDate: "2024-07-26",
    messageId: "msg-k1l2m3n4o5",
    confidence: 99,
    status: "Verified",
  },
  {
    timestamp: "2024-07-21T11:00:00Z",
    interactionType: "New Request",
    customer: "HeavyHaul Logistics",
    originCity: "Denver",
    originState: "CO",
    destinationCity: "Houston",
    destinationState: "TX",
    equipment: "Flatbed",
    weight: "48,000 lbs",
    targetPrice: "$3200",
    pickupDate: "2024-07-26",
    deliveryDate: "N/A",
    messageId: "msg-p6q7r8s9t0",
    confidence: 96,
    status: "Logged",
  },
  {
    timestamp: "2024-07-20T09:12:00Z",
    interactionType: "Follow-up",
    customer: "CrossCountry Carriers",
    originCity: "Phoenix",
    originState: "AZ",
    destinationCity: "Portland",
    destinationState: "OR",
    equipment: "Dry Van",
    weight: "N/A",
    targetPrice: "$2,000",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-u1v2w3x4y5",
    confidence: 85,
    status: "Logged",
  },
  {
    timestamp: "2024-07-20T08:30:00Z",
    interactionType: "New Request",
    customer: "FreshDirect Produce",
    originCity: "Fresno",
    originState: "CA",
    destinationCity: "Boston",
    destinationState: "MA",
    equipment: "Reefer",
    weight: "38,000 lbs",
    targetPrice: "$4500",
    pickupDate: "2024-07-28",
    deliveryDate: "2024-08-02",
    messageId: "msg-z6a7b8c9d0",
    confidence: 94,
    status: "Verified",
  },
  {
    timestamp: "2024-07-19T15:00:00Z",
    interactionType: "Quote Sent",
    customer: "SteelWorks",
    originCity: "Pittsburgh",
    originState: "PA",
    destinationCity: "Detroit",
    destinationState: "MI",
    equipment: "Dry Van",
    weight: "44,000 lbs",
    targetPrice: "$950",
    pickupDate: "2024-07-22",
    deliveryDate: "2024-07-23",
    messageId: "msg-e1f2g3h4i5",
    confidence: 99,
    status: "Logged",
  },
  {
    timestamp: "2024-07-19T13:20:00Z",
    interactionType: "New Request",
    customer: "Parts Express",
    originCity: "Newark",
    originState: "NJ",
    destinationCity: "Philadelphia",
    destinationState: "PA",
    equipment: "Dry Van",
    weight: "2,000 lbs",
    targetPrice: "$400",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-j6k7l8m9n0",
    confidence: 91,
    status: "Logged",
  },
  {
    timestamp: "2024-07-19T10:05:00Z",
    interactionType: "Follow-up",
    customer: "LogiTrans LLC",
    originCity: "Dallas",
    originState: "TX",
    destinationCity: "Atlanta",
    destinationState: "GA",
    equipment: "Dry Van",
    weight: "42,000 lbs",
    targetPrice: "$2500",
    pickupDate: "2024-07-25",
    deliveryDate: "2024-07-28",
    messageId: "msg-o1p2q3r4s5",
    confidence: 82,
    status: "Logged",
  },
  {
    timestamp: "2024-07-18T17:00:00Z",
    interactionType: "New Request",
    customer: "BuildMart Supplies",
    originCity: "Salt Lake City",
    originState: "UT",
    destinationCity: "Las Vegas",
    destinationState: "NV",
    equipment: "Flatbed",
    weight: "45,000 lbs",
    targetPrice: "$1800",
    pickupDate: "2024-07-29",
    deliveryDate: "2024-08-02",
    messageId: "msg-t6u7v8w9x0",
    confidence: 93,
    status: "Logged",
  },
  {
    timestamp: "2024-07-18T14:10:00Z",
    interactionType: "Quote Sent",
    customer: "QuickShip Inc.",
    originCity: "Chicago",
    originState: "IL",
    destinationCity: "Miami",
    destinationState: "FL",
    equipment: "Dry Van",
    weight: "40,000 lbs",
    targetPrice: "$3,500",
    pickupDate: "2024-07-20",
    deliveryDate: "2024-07-23",
    messageId: "msg-y1z2a3b4c5",
    confidence: 98,
    status: "Verified",
  },
  {
    timestamp: "2024-07-17T11:45:00Z",
    interactionType: "Follow-up",
    customer: "Global Movers",
    originCity: "Los Angeles",
    originState: "CA",
    destinationCity: "Seattle",
    destinationState: "WA",
    equipment: "Reefer",
    weight: "35,000 lbs",
    targetPrice: "$2,800",
    pickupDate: "2024-07-24",
    deliveryDate: "2024-07-26",
    messageId: "msg-d6e7f8g9h0",
    confidence: 90,
    status: "Logged",
  },
  {
    timestamp: "2024-07-17T10:00:00Z",
    interactionType: "New Request",
    customer: "Agri-Source",
    originCity: "Omaha",
    originState: "NE",
    destinationCity: "Kansas City",
    destinationState: "MO",
    equipment: "Hopper Bottom",
    weight: "50,000 lbs",
    targetPrice: "$1100",
    pickupDate: "N/A",
    deliveryDate: "N/A",
    messageId: "msg-i1j2k3l4m5",
    confidence: 89,
    status: "Logged",
  },
  {
    timestamp: "2024-07-16T09:30:00Z",
    interactionType: "Follow-up",
    customer: "SteelWorks",
    originCity: "Pittsburgh",
    originState: "PA",
    destinationCity: "Detroit",
    destinationState: "MI",
    equipment: "Dry Van",
    weight: "44,000 lbs",
    targetPrice: "$950",
    pickupDate: "2024-07-22",
    deliveryDate: "2024-07-23",
    messageId: "msg-n6o7p8q9r0",
    confidence: 75,
    status: "Logged",
  },
  {
    timestamp: "2024-07-15T14:00:00Z",
    interactionType: "New Request",
    customer: "ChemTransport",
    originCity: "Baton Rouge",
    originState: "LA",
    destinationCity: "Memphis",
    destinationState: "TN",
    equipment: "Tanker",
    weight: "40,000 lbs",
    targetPrice: "$1500",
    pickupDate: "2024-08-01",
    deliveryDate: "N/A",
    messageId: "msg-s1t2u3v4w5",
    confidence: 92,
    status: "Verified",
  },
  {
    timestamp: "2024-07-15T10:00:00Z",
    interactionType: "New Request",
    customer: "General Goods",
    originCity: "Columbus",
    originState: "OH",
    destinationCity: "Richmond",
    destinationState: "VA",
    equipment: "Dry Van",
    weight: "25,000 lbs",
    targetPrice: "$1900",
    pickupDate: "2024-07-20",
    deliveryDate: "2024-07-22",
    messageId: "msg-a1b2c3d4e5",
    confidence: 97,
    status: "Logged",
  },
  {
    timestamp: "2024-07-14T16:20:00Z",
    interactionType: "Quote Sent",
    customer: "Paper Co.",
    originCity: "Savannah",
    originState: "GA",
    destinationCity: "Jacksonville",
    destinationState: "FL",
    equipment: "Dry Van",
    weight: "43,000 lbs",
    targetPrice: "$800",
    pickupDate: "2024-07-18",
    deliveryDate: "2024-07-19",
    messageId: "msg-f6g7h8i9j0",
    confidence: 99,
    status: "Logged",
  },
  {
    timestamp: "2024-07-14T11:50:00Z",
    interactionType: "New Request",
    customer: "Machinery World",
    originCity: "Milwaukee",
    originState: "WI",
    destinationCity: "Minneapolis",
    destinationState: "MN",
    equipment: "Step-deck",
    weight: "30,000 lbs",
    targetPrice: "$1300",
    pickupDate: "2024-07-19",
    deliveryDate: "N/A",
    messageId: "msg-k1l2m3n4o6",
    confidence: 93,
    status: "Logged",
  },
  {
    timestamp: "2024-07-13T14:00:00Z",
    interactionType: "Follow-up",
    customer: "General Goods",
    originCity: "Columbus",
    originState: "OH",
    destinationCity: "Richmond",
    destinationState: "VA",
    equipment: "Dry Van",
    weight: "25,000 lbs",
    targetPrice: "$1900",
    pickupDate: "2024-07-20",
    deliveryDate: "2024-07-22",
    messageId: "msg-p6q7r8s9t1",
    confidence: 81,
    status: "Logged",
  },
  {
    timestamp: "2024-07-13T09:05:00Z",
    interactionType: "New Request",
    customer: "PharmaCorp",
    originCity: "Indianapolis",
    originState: "IN",
    destinationCity: "St. Louis",
    destinationState: "MO",
    equipment: "Reefer",
    weight: "15,000 lbs",
    targetPrice: "$900",
    pickupDate: "2024-07-17",
    deliveryDate: "2024-07-18",
    messageId: "msg-u1v2w3x4y6",
    confidence: 96,
    status: "Verified",
  },
  {
    timestamp: "2024-07-12T18:00:00Z",
    interactionType: "Quote Sent",
    customer: "BuildMart Supplies",
    originCity: "Salt Lake City",
    originState: "UT",
    destinationCity: "Las Vegas",
    destinationState: "NV",
    equipment: "Flatbed",
    weight: "45,000 lbs",
    targetPrice: "$1,800",
    pickupDate: "2024-07-16",
    deliveryDate: "2024-07-17",
    messageId: "msg-z6a7b8c9d1",
    confidence: 99,
    status: "Logged",
  },
  {
    timestamp: "2024-07-12T15:30:00Z",
    interactionType: "New Request",
    customer: "Coastal Fisheries",
    originCity: "Mobile",
    originState: "AL",
    destinationCity: "New Orleans",
    destinationState: "LA",
    equipment: "Reefer",
    weight: "20,000 lbs",
    targetPrice: "$750",
    pickupDate: "2024-07-15",
    deliveryDate: "2024-07-15",
    messageId: "msg-e1f2g3h4i6",
    confidence: 94,
    status: "Logged",
  },
  {
    timestamp: "2024-07-11T13:00:00Z",
    interactionType: "Follow-up",
    customer: "PharmaCorp",
    originCity: "Indianapolis",
    originState: "IN",
    destinationCity: "St. Louis",
    destinationState: "MO",
    equipment: "Reefer",
    weight: "15,000 lbs",
    targetPrice: "$900",
    pickupDate: "2024-07-17",
    deliveryDate: "2024-07-18",
    messageId: "msg-j6k7l8m9n1",
    confidence: 84,
    status: "Logged",
  },
  {
    timestamp: "2024-07-11T10:10:00Z",
    interactionType: "New Request",
    customer: "Office Supplies Inc.",
    originCity: "Charlotte",
    originState: "NC",
    destinationCity: "Nashville",
    destinationState: "TN",
    equipment: "Dry Van",
    weight: "33,000 lbs",
    targetPrice: "$1200",
    pickupDate: "2024-07-16",
    deliveryDate: "N/A",
    messageId: "msg-o1p2q3r4s6",
    confidence: 95,
    status: "Logged",
  },
  {
    timestamp: "2024-07-10T11:00:00Z",
    interactionType: "Quote Sent",
    customer: "ChemTransport",
    originCity: "Baton Rouge",
    originState: "LA",
    destinationCity: "Memphis",
    destinationState: "TN",
    equipment: "Tanker",
    weight: "40,000 lbs",
    targetPrice: "$1,500",
    pickupDate: "2024-07-13",
    deliveryDate: "2024-07-14",
    messageId: "msg-t6u7v8w9x1",
    confidence: 98,
    status: "Verified",
  },
];
